#!/bin/bash
## Job Name
#SBATCH --job-name=b_0
## Allocation Definition
#SBATCH --account=chem-ckpt
#SBATCH --partition=ckpt
## Resources
## Nodes
#SBATCH --nodes=1
## Tasks per node (28 is Slurm default)
#SBATCH --ntasks-per-node=28
## Walltime (days-HH:MM:SS)
#SBATCH --time=15:00:00
## Memory per node
#SBATCH --mem=80G
##Output file
#SBTACH --output cfs.out

module load anaconda3_4.3.1

# Get shape file and initial input files

# Gaussian raster scattering
yrange=200
ystart=-200
yend=$ystart+$yrange
ss=10
z=0

# Initial set up & scattering calculation 
for ((y=$ystart;y<=$yend;y+=$ss));do
    mkdir x00_y${y}_z${z}; cd x00_y${y}_z${z}
    cp ../shape.f90 .
    sed -i "s/rastery = 0/rastery =  ${y}/" shape.f90
    sed -i "s/rasterz = 0/rasterz = ${z}/" shape.f90
    gfortran shape.f90 && ./a.out
    cp ../makemetal_temp.py .
    cp ../input_generator.py .; cp ../parameters.input .
    python input_generator.py -d parameters.input shape.dat
    python input_generator.py -v parameters.input shape.dat
    /usr/lusers/clairew4/src-gaussian/ddscat &> x00_y${y}_z${z}_DDApump.out &
    cd ..
done; wait

# Rename files
for ((y=$ystart;y<=$yend;y+=$ss));do
    cd x00_y${y}_z${z}
    mv ddscat.par ddscat.par_pump; cp shape.dat shape.dat_pump
    mv qtable qtable_pump; rm qtable2; rm mtable
    rm Einc_w000_ddscat.par; rm EBsca_w000_ddscat.par; mv tdda_input_w000_ddscat.par tdda_input
    rm Integration_f11f11
    cd ..
done; echo 'Finished all pump scattering calculations'

# tDDA calculation
for ((y=$ystart;y<=$yend;y+=$ss));do
    cd x00_y${y}_z${z}
    /gscratch/chem/masiello_group/tDDA_1123_sub_plane/Lattice_Diffusion /gscratch/chem/masiello_group/myGreen.num_300 var.par tdda_input temp.out &> x00_y${y}_z${z}_tDDA.out &
    cd ..
done; wait; echo 'Temperature calculations finished'

# Probe calculations
for ((y=$ystart;y<=$yend;y+=$ss));do
    cd x00_y${y}_z${z}
    python ../check_temp.py temp.out
    mv shape.dat shape.dat_pump
    python input_generator.py -p parameters.input shape.dat_pump
    python makemetal.py
    python input_generator.py -dN parameters.input shape.dat_pump shape.dat ddscat_filler n_T_of_temp_max
    /usr/lusers/clairew4/src-gaussian/ddscat &> x00_y${y}_z${z}_DDAprobe.out &
    cd ..
done; wait

# Rename after jobs are finished
for ((y=$ystart;y<=$yend;y+=$ss));do
    cd x00_y${y}_z${z}
    mv ddscat.par ddscat.par_hot;
    mv qtable qtable_hot; rm qtable2; rm mtable
    rm Einc_w000_ddscat.par; rm makemetal_temp.py; rm ddscat_filler; rm temp-shift.txt
    mv Integration_f11f11 Integration_f11f11_hot
    cd ..
done; wait; echo 'Probe scattering calculation finished' 

###################################################################################
### Room temperature calculation ###
###################################################################################


#Initial set up & scattering calculation

for ((y=$ystart;y<=$yend;y+=$ss));do
    cd x00_y${y}_z${z}
    cp ../shape.f90 .
    sed -i "s/rastery = 0/rastery =  ${y}/" shape.f90
    sed -i "s/rasterz = 0/rasterz = ${z}/" shape.f90
    gfortran shape.f90 && ./a.out
    cp ../input_generator.py .; cp ../parameters.input .
    python input_generator.py -d parameters.input shape.dat
    python input_generator.py -dR parameters.input shape.dat
    /usr/lusers/clairew4/src-gaussian/ddscat &> x00_y${y}_z${z}_DDAroom.out &
    cd ..
done; wait

for ((y=$ystart;y<=$yend;y+=$ss));do
    cd x00_y${y}_z${z}
    mv ddscat.par ddscat.par_room; cp shape.dat shape.dat_room
    mv qtable qtable_room; rm qtable2; rm mtable
    rm Einc_w000_ddscat.par;
    mv Integration_f11f11 Integration_f11f11_room
    cd ..
done; echo 'all good girl'
wait 

# ################################################################################### 
# ### Collect Data ###                                                               
# ###################################################################################   
# bash collect_all.sh

